NEZNAMY/TAB

.gitignore
src/me/neznamy/tab/platforms/bukkit/Main.java
src/me/neznamy/tab/platforms/bungee/Main.java
src/me/neznamy/tab/platforms/velocity/Main.java
src/me/neznamy/tab/premium/Premium.java
src/me/neznamy/tab/premium/Scoreboard.java
src/me/neznamy/tab/shared/Animation.java
src/me/neznamy/tab/shared/BossBar.java
src/me/neznamy/tab/shared/Configs.java
src/me/neznamy/tab/shared/ConfigurationFile.java
src/me/neznamy/tab/shared/ITabPlayer.java
src/me/neznamy/tab/shared/Playerlist.java
src/me/neznamy/tab/shared/PluginHooks.java
src/me/neznamy/tab/shared/Shared.java
src/me/neznamy/tab/shared/placeholders/Placeholders.java

Just some very minor fixes I thought you might appreciate that make developing/building on a different machine easier:
* Changed `§` from platform-specific character to UTF-8 encoding version
* Fixed typo: `occured` -> `occurred`
* Added `.idea` to the gitignore to prevent IntelliJ project files getting committed

Change section sign encoding to UTF-8

---

pom.xml
src/main/java/bungee.yml
src/main/java/plugin.yml
src/main/java/velocity-plugin.json

Revert "Use variable filtering for version in plugin.yml/bungee.yml/velocity-plugin.json"

---

pom.xml

The first time I have undone a relocation.

Unrelocate json-simple

---

src/main/java/me/neznamy/tab/shared/RGBUtils.java

Hi! Just added a little something that enables support for [Iridescent's](https://www.spigotmc.org/resources/%E2%9C%8F%EF%B8%8F-iridescent-%E2%9C%8F%EF%B8%8F-1-16-x-add-new-hex-colors-to-your-server-supports-gradients.81322/) style of tags. I thought might be nice to have going forward as the plugin has picked up some traction recently (I don't see it causing any issues since it's a very small change). 
If you wish to make any edits then feel free. I also understand if you wish to reject this pull request since it's your plugin at the end of the day.
Thanks.

Added support for Iridescent style gradient tags.

---

src/main/java/me/neznamy/tab/premium/conditions/simple/EqualsCondition.java
src/main/java/me/neznamy/tab/premium/conditions/simple/NotEqualsCondition.java

As simple as that, yeah, I hope I can try to make some more pr in the future to help

Parse placeholder on right side of condition

---

src/main/java/me/neznamy/tab/platforms/bungee/Main.java

Reading this here may help you understand future problems: https://netty.io/wiki/reference-counted-objects.html

Fix ByteBuf memory ref leak

---

pom.xml

I think Essentials changed the repository

Fix Essentials repository

---

src/main/java/me/neznamy/tab/shared/rgb/RGBUtils.java

What the title says, removed the legacy addon as it is only in the mimic of kyori gradients

Added an extra gradient pattern in the style of Kyori

---

bukkit/pom.xml
bukkit/src/main/java/me/neznamy/tab/platforms/bukkit/BukkitPacketBuilder.java
bukkit/src/main/java/me/neznamy/tab/platforms/bukkit/BukkitTabPlayer.java
shared/src/main/java/me/neznamy/tab/shared/ProtocolVersion.java

Tested on 1.17 and the bossbar showed up with no error in console.

Update to ViaVersion 4.0.0

---

bukkit/pom.xml
bukkit/src/main/java/me/neznamy/tab/platforms/bukkit/BukkitPlaceholderRegistry.java
bukkit/src/main/java/me/neznamy/tab/platforms/bukkit/Main.java
shared/src/main/java/me/neznamy/tab/shared/TAB.java

Sorry it took me a while, had to make sure it worked on server

Add %mspt% (simplified)

---

jar/pom.xml
krypton/pom.xml
krypton/src/main/kotlin/me/neznamy/tab/platforms/krypton/KryptonEventListener.kt
krypton/src/main/kotlin/me/neznamy/tab/platforms/krypton/KryptonPacketBuilder.kt
krypton/src/main/kotlin/me/neznamy/tab/platforms/krypton/KryptonPipelineInjector.kt
krypton/src/main/kotlin/me/neznamy/tab/platforms/krypton/KryptonPlaceholderRegistry.kt
krypton/src/main/kotlin/me/neznamy/tab/platforms/krypton/KryptonPlatform.kt
krypton/src/main/kotlin/me/neznamy/tab/platforms/krypton/KryptonTabPlayer.kt
krypton/src/main/kotlin/me/neznamy/tab/platforms/krypton/Main.kt
krypton/src/main/kotlin/me/neznamy/tab/platforms/krypton/event/TabLoadEvent.kt
krypton/src/main/kotlin/me/neznamy/tab/platforms/krypton/event/TabPlayerLoadEvent.kt
krypton/src/main/kotlin/me/neznamy/tab/platforms/krypton/features/PerWorldPlayerList.kt
krypton/src/main/kotlin/me/neznamy/tab/platforms/krypton/features/unlimitedtags/KryptonArmorStand.kt
krypton/src/main/kotlin/me/neznamy/tab/platforms/krypton/features/unlimitedtags/NameTagX.kt
krypton/src/main/kotlin/me/neznamy/tab/platforms/krypton/features/unlimitedtags/PacketListener.kt
krypton/src/main/resources/bukkitconfig.yml
pom.xml

This PR adds support for the Krypton Minecraft server software. More information on this platform can be found [here](https://github.com/KryptonMC/Krypton) if interested.
This has been tested on Krypton 0.47, and, with all things Krypton, only the latest version is supported. Support for previous versions of Krypton will not be provided.
In addition, as agreed on Discord, I will maintain this myself, which will include updating to new Krypton versions, adding new feature support as they get added in to Krypton, and also providing support for those who are using the plugin on the Krypton platform.
There is one thing here that I do need to address, which is the fact that this is all written using 4 spaces for indentation, whereas the rest of the project uses 8 spaces. If necessary, on …

Added support for Krypton

---

jar/pom.xml
krypton/pom.xml
krypton/src/main/kotlin/me/neznamy/tab/platforms/krypton/KryptonPlaceholderRegistry.kt
krypton/src/main/kotlin/me/neznamy/tab/platforms/krypton/Main.kt

Revert "Made Krypton a separate JAR"

---

shared/src/main/java/me/neznamy/tab/shared/command/WidthCommand.java

- Added more tab completion
- Added /tab width set
- For numbers <10 it will use the number itself, for numbers >= 10 it will use the character ID

Further improve Width command

---

.github/workflows/build.yml

As in title, hope you like it.

Setup workflow artifact

---

velocity/src/main/java/me/neznamy/tab/platforms/velocity/VelocityPlaceholderRegistry.java

Now it's showing the number of players who are vanish. lol

Correctly display the number of players online.

---

api/src/main/java/me/neznamy/tab/api/chat/rgb/RGBUtils.java
api/src/main/java/me/neznamy/tab/api/chat/rgb/format/KyoriFormat.java

Add support for Kyori MiniMessage RGB format

---

gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
shared/src/main/java/me/neznamy/tab/shared/features/layout/skin/Texture.java
velocity/src/main/java/me/neznamy/tab/platforms/velocity/Main.java
velocity/src/main/java/me/neznamy/tab/platforms/velocity/VelocityTabPlayer.java

Yes I know its not in the jar but still nice to keep it up to date for people wanting to use it by compiling themselves

Updates and Velocity Deprecation Fix

---

api/src/main/java/me/neznamy/tab/api/scoreboard/ScoreboardManager.java
shared/src/main/java/me/neznamy/tab/shared/features/scoreboard/ScoreboardManagerImpl.java

Basically I just fixed annotation. Sad what I found out the typo only after I got NullPointerException

@NotNull marked function actually can return null

---

shared/src/main/java/me/neznamy/tab/shared/chat/rgb/RGBUtils.java
shared/src/main/java/me/neznamy/tab/shared/chat/rgb/gradient/NexEngineGradient.java

https://github.com/nulli0n/NexEngine-spigot/wiki/Configuration-Tips

Add NexEngine gradient

---

build-logic/build.gradle.kts
fabric/build.gradle.kts
fabric/src/main/java/me/neznamy/tab/platforms/fabric/FabricPlatform.java
fabric/src/main/java/me/neznamy/tab/platforms/fabric/hook/FabricTabExpansion.java
fabric/v1_14_4/build.gradle.kts
fabric/v1_18_2/build.gradle.kts
fabric/v1_20_3/build.gradle.kts
sponge8/build.gradle.kts

Added support for [Text PlaceholderAPI](https://modrinth.com/mod/placeholder-api) when TAB is on Fabric
Unsure if all placeholders will work, but I'm guessing most player & server placeholders should work
Also added mavenCentral() to the Sponge 8 repos because it couldn't fetch some dependency off jitpack anymore, preventing me from compiling the plugin...

Added Text PlaceholderAPI support on Fabric

---

shared/src/main/java/me/neznamy/tab/shared/TabConstants.java
shared/src/main/java/me/neznamy/tab/shared/hook/LuckPermsHook.java
shared/src/main/java/me/neznamy/tab/shared/placeholders/UniversalPlaceholderRegistry.java

Added %luckperms-weight% as a built-in placeholder

---

bukkit/src/main/java/me/neznamy/tab/platforms/bukkit/scoreboard/viaversion/ViaScoreboard.java
bukkit/src/main/java/me/neznamy/tab/platforms/bukkit/tablist/viaversion/ViaTabList.java

New and improved packet sending:
* Player enter to server
* ViaVersion decoder is registered while player is on LOGIN state
* TAB plugin queue packets
* Player go to CONFIGURATION state
* Player go to PLAY state
* TAB send queued packets and start working normally

Fix ViaVersion packets delay
