NEZNAMY/TAB

- src/me/neznamy/tab/platforms/bukkit/Injector.java
- src/me/neznamy/tab/platforms/bukkit/Injector1_7.java
- src/me/neznamy/tab/platforms/bukkit/Main.java
- src/me/neznamy/tab/platforms/bukkit/unlimitedtags/NameTagX.java
- src/me/neznamy/tab/platforms/bungee/Main.java
- src/me/neznamy/tab/platforms/velocity/Main.java
- src/me/neznamy/tab/shared/ITabPlayer.java
- src/me/neznamy/tab/shared/PluginHooks.java
- src/me/neznamy/tab/shared/Shared.java
- src/me/neznamy/tab/shared/placeholders/Placeholder.java
- src/org/json/simple/parser/Yylex.java
Basically the entire plugin will not enable correctly for anyone with config generated before the improved `per-world-settings` config changes recently added (2.5.5-pre9).
This is because of an incorrect data type:
* Old (list): 
```
per-world-settings: []
```
* New (map): 
```
per-world-settings:
world1:
header:
- "an example of world with custom"
footer:
- "header/footer and prefix/suffix"
Groups:
Owner:
tabprefix: "&0&l[&a&lOwner&0&l] &a"
tagprefix: "&2&lOwner &a"
world2-world3:
header:
- "This is a shared header for"
- "world2 and world3"
```
I fixed this without any notification but ideally a warning message should be logged or config should be auto-updated.
I also ran an auto-format on the ITabPlayer file, fixed an incorrect spelling (occured -> occurred) and replaced a String loop …
> Handle old per-world-settings config; typo: occured -> occuRRed

- src/me/neznamy/tab/platforms/bukkit/features/unlimitedtags/NameTagX.java
Whenever a player respawns, the nametag will not update its position until said player starts moving, usually showing at the place of death until so. I simply copied the content of the PlayerTeleportEvent handler to paste into a new PlayerRespawnEvent one, while adjusting the measured task title accordingly.
Tested this on a 1.15.2 paper-spigot server, worked fine.
> Fixing nametag position issue

- src/main/java/me/neznamy/tab/platforms/bukkit/features/TabExpansion.java
Instead of only get the default properties, this allows to get all loaded properties.
It would for example allow users to get the Unlimited Nametag Lines properties or also the properties from other plugins such as mine :D
> Make %tab_<property>% support any loaded property 

- pom.xml
Without this commit, Maven will attempt to pull down ViaVersion from Spigot instead of the ViaVersion repo.
```
[INFO] ---------------------------< me.neznamy:TAB >---------------------------
[INFO] Building TAB 2.8.8
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for us.myles:viaversion:jar:3.2.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.317 s
[INFO] Finished at: 2020-11-04T09:12:46-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project TAB: Could not resolve …
```
> Added ViaVersion maven repo

- src/main/java/me/neznamy/tab/platforms/bukkit/placeholders/BukkitPlaceholderRegistry.java
Hey NEZ,
here's a fix for placeholders such as %tps% that returns , instead of .
> Fixed placeholders numbers locale format

- src/main/java/me/neznamy/tab/shared/command/level2/AnnounceBarCommand.java
Fix bossbar toggle not being respected when the `/tab announce bar` command is executed
> Fix bossbar toggle not being respected

- src/main/java/me/neznamy/tab/shared/FeatureManager.java
I think there's a typo in the onHeaderFooter method in FeatureManager.java. This leads to that the cpu usage for deserialization will be calculated for the wrong type of packet.
https://github.com/NEZNAMY/TAB/blob/9f3995198b2d6bd84d188f5a93bb78fb785e6ee7/src/main/java/me/neznamy/tab/shared/FeatureManager.java#L330-L333
I changed it to the packet header and footer usage type, so that the cpu usage will be correct.
> Fix using wrong cpu usage deserialization packet type

- shared/src/main/java/me/neznamy/tab/shared/features/sorting/types/Groups.java
Remove unnecessary (and incorrectly shown) color code from "Group is not defined in sorting list!" error message
> Remove unnecessary color code

- shared/src/main/java/me/neznamy/tab/shared/command/WidthCommand.java
Improvements I made:
- ID of the character is now displayed in the title when sending the width
- Better error handling
- You can now enter something like `/tab width Ä 15` to send 15 messages instead of 10 **(It's essential for adjusting the width for rank images characters, as those are longer than 10 characters)**
- Cleaned up the code a little and improved the Usage: messages
> Improve /tab width command

- bungeecord/src/main/resources/bungee.yml
When BungeeTabPlayer#isVanished uses PV's API, PV needs to actually be enabled, not just loaded. A soft-dependency should ensure that PV is fully enabled before TAB's onEnable() uses the API. It doesn't look like Bungee's PluginManager has a Plugin#isEnabled method.
This should fix [this error](https://pastebin.com/5B0ia4Vc ) that someone reported to me.
> Load TAB after PremiumVanish

- bukkit/src/main/java/me/neznamy/tab/platforms/bukkit/BukkitPlaceholderRegistry.java
I was trying to color code the '%mspt%' placeholder on a server with a German locale. The issue was that the decimal separator in Germany is a comma ',' which the number comparing logic ignored. So my fix was to just change the locale to English so it would work in any case.
The error looked like this:
32,496 became 32496.0
> Fixed localization issue when dealing with floats numbers

- shared/src/main/resources/messages.yml
it seems new update `/tab ntpreview` has been replaced with `/tab nametag preview`
Help text was not updated
> fix nametag preview help text

- gradle/libs.versions.toml
snakeyaml 1.30 is affected by 5 vulnerabilities and should be upgraded to the latest version
> bump org.yaml:snakeyaml to 1.33

- LICENSE
While auditing my server for license compliance, I noticed that TAB is missing one. On the [Modrinth](https://modrinth.com/plugin/tab-was-taken) page, it's categorized as an Apache 2.0 plugin. This commit proposes adopting Apache 2.0 into the source tree. Thank you for your consideration.
- Alex Noyle
> Propose adopting open source license

- bukkit/src/main/java/me/neznamy/tab/platforms/bukkit/BukkitEventListener.java
Explanation:
Both TAB and ViaVersion PlayerJoinEvent priority are LOWEST and seems that TAB registers earlier than ViaVersion the listeners, this causes TAB not being able to get the client protocol version due to ViaVersion not being able to register it firstly.
There might be another way to workaround this since i don't know changing the priority would cause any issue with TAB itself.
> Fix ViaVersion bug returning -1 version

- shared/src/main/java/me/neznamy/tab/shared/features/layout/FixedSlot.java
- shared/src/main/java/me/neznamy/tab/shared/features/layout/LayoutManagerImpl.java
- shared/src/main/java/me/neznamy/tab/shared/features/layout/LayoutPattern.java
- shared/src/main/java/me/neznamy/tab/shared/features/layout/LayoutView.java
- shared/src/main/java/me/neznamy/tab/shared/features/layout/ParentGroup.java
- shared/src/main/java/me/neznamy/tab/shared/features/layout/PlayerSlot.java
- shared/src/main/java/me/neznamy/tab/shared/features/layout/skin/SkinManager.java
I have added support for different default skins depending on the slot index to allow you to customize the tab list even further.  If a slot doesn't have a default skin specified "layout.default-skin" will be used as before.
Here is an example of what a configuration with different default-skins could look like.
```yaml
default-skins:
green:
slots:
- 0-40
skin: mineskin:dd999400b7eb42288d62f8066a74f2b8
yellow:
slots: 
- 41-60
skin: mineskin:20f93edf53784fdc96e62affc9b7087e
red:
slots: 
- 61-80
skin: mineskin:7bc1ef76b2cc41b59067ca409be76e5a
default-skin: mineskin:dd999400b7eb42288d62f8066a74f2b8
```
With this added functionality you can make something like this:
> Added support for different default skins depending on the slot index in the layout feature

- bukkit/src/main/java/me/neznamy/tab/platforms/bukkit/nms/DataWatcher.java
This issue has been reported to Arclight, but the developer has not responded yet
I tried to find the problem and successfully fixed it
This problem arises from the existence of two void markDirty methods in Arclight
causes an exception to be thrown
https://github.com/IzzelAliz/Arclight/blob/Trials/arclight-common/src/main/java/io/izzel/arclight/common/mixin/core/network/SynchedEntityDataMixin.java#L49
https://github.com/IzzelAliz/Arclight/issues/1087
> Fix Arclight compatibility

- shared/src/main/java/me/neznamy/tab/shared/config/Configs.java
- shared/src/main/java/me/neznamy/tab/shared/config/file/YamlPropertyConfigurationFile.java
- shared/src/main/java/me/neznamy/tab/shared/features/HeaderFooter.java
Adds support for using Global Playerlist `server-groups` config keys in the Header/Footer `per-server` section.
This allows for configuration of a server group with several velocity/bungee servers which can have a matching config key in the per-server header/footer section.
Example:
```yml
header-footer:
per-server:
hubs:
header: [] #Tab Details Here
footer: [] #Tab Details Here
global-playerlist:
server-groups:
hubs:
- hub1 # Bungee/Velocity server name
- hub2 # Bungee/Velocity server name
```
This makes config a little easier and more intuitive because adding another server with a custom TAB is as simple as adding to the global playerlist `server-groups` group, which is then used by header/footer per-server.
> Support to use Global Playerlist `server-groups` as Header/Footer `per-server` keys.

- sponge8/src/main/java/me/neznamy/tab/platforms/sponge8/Sponge8TAB.java
SpongeForge crashes with the following message `File /path/to/plugin/TAB.v4.1.2.jar constructed 0 mods: [], but had 1 mods specified: [tab]`
I have tested the following versions:
- 1.16.5-36.2.5-8.2.1-RC1459
- 1.16.5-36.2.5-8.2.0
This can be fixed by putting an `@Plugin("tab")` annotation on the main Sponge 8 class.
> Fix SpongeForge startup crash

- .github/workflows/build.yml
This PR adds the GitHub build number at the end of the file. This makes it easier to organize and track updates for people that use GitHub actions to download the plugin.
Example:
- Previous output: TAB-5.0.0-SNAPSHOT
- New output: TAB-5.0.0-SNAPSHOT+5
> [GitHub] Add build number to artifact

- shared/src/main/java/me/neznamy/tab/shared/features/layout/skin/SignedTexture.java
- shared/src/main/java/me/neznamy/tab/shared/features/layout/skin/SkinManager.java
I'm adding a `signed_texture` parameter in the skin retrieval process, **which avoids an API call**. For this, I use `signed_texture:texture;signature` in the skin retrieval.
> Add a signed_texture skin parameter to avoid an API call

- bungeecord/src/main/java/me/neznamy/tab/platforms/bungeecord/BungeeTabPlayer.java
- sponge8/src/main/java/me/neznamy/tab/platforms/sponge8/SpongeTabPlayer.java
- velocity/src/main/java/me/neznamy/tab/platforms/velocity/VelocityTabPlayer.java
The current implementation of `getSkin()` on some platforms simply takes the first property of the profile properties as the skin texture, which can cause problems if multiple properties are returned and the skin texture is not the first. Therefore, it may be better to get the skin texture by property name to ensure that other properties won't be mistaken for the skin texture.
> Get skin from profile properties by property name

- api/src/main/java/me/neznamy/tab/api/integration/VanishIntegration.java
- bukkit/src/main/java/me/neznamy/tab/platforms/bukkit/hook/BukkitPremiumVanishHook.java
- bukkit/src/main/java/me/neznamy/tab/platforms/bukkit/platform/BukkitPlatform.java
- bungeecord/src/main/java/me/neznamy/tab/platforms/bungeecord/BungeePlatform.java
- bungeecord/src/main/java/me/neznamy/tab/platforms/bungeecord/BungeeTabPlayer.java
- bungeecord/src/main/java/me/neznamy/tab/platforms/bungeecord/hook/BungeePremiumVanishHook.java
- shared/src/main/java/me/neznamy/tab/shared/hook/PremiumVanishHook.java
- shared/src/main/java/me/neznamy/tab/shared/platform/Platform.java
- velocity/src/main/java/me/neznamy/tab/platforms/velocity/VelocityPlatform.java
- velocity/src/main/java/me/neznamy/tab/platforms/velocity/hook/VelocityPremiumVanishHook.java
This update introduces a new `VanishIntegration` API to enhance support for vanish plugins, such as PremiumVanish, without requiring TAB to directly rely on their APIs. Previously, TAB needed to interact with plugin-specific APIs, making integration more rigid.  
With the new system:  
- Developers can integrate vanish plugins externally without modifying TAB's core code.  
- The existing PremiumVanish integration has been migrated to use the new API within TAB itself. However, the developer of PremiumVanish can adopt the new API to manage the integration independently, allowing TAB to eventually remove the built-in integration.  
- Other vanish plugins can now seamlessly hook into the API to tailor TAB’s behavior according to their needs.  
I tested the new API with my own plugin, …
> feat: add VanishIntegration api

- shared/src/main/java/me/neznamy/tab/shared/platform/Platform.java
- shared/src/main/java/me/neznamy/tab/shared/proxy/ProxyTabPlayer.java
This update ensures that TAB does not check the "vanished" meta if a vanish integration is registered. The redundant check was causing issues with the `canSee` functionality in specific scenarios:  
- A player has the "vanished" meta set (i.e., `isVanished` is true).  
- The registered vanish integration correctly returns `true` for `canSee`.  
- Because `canSee` is true inside integration, TAB continues to check the "vanished" meta. Since the meta indicates the player is vanished, TAB incorrectly overrides the integration’s `canSee` result and returns `false`. 
By skipping the "vanished" meta check when a registered vanish integration is present, this fix ensures the `canSee` behavior aligns with the integration’s logic.
> fix: avoid using TAB's internal vanish checks when a registered vanish integration is available

- fabric/src/main/java/me/neznamy/tab/platforms/fabric/FabricPlatform.java
Added Fabric TPS approximation, based on mspt.
If the mspt is under 50t (1000ms/20t -> 50ms/t minimum for 20tps), it will be 20tps; otherwise, it would be inversely proportional to time (1000ms/mspt -> tps).
Also, it's rounded in case the double is not reformatted before being displayed in the tab.
> Fabric now has a getTPS() approximation.
